theme: jekyll-theme-minimal

# Site settings
# The title of your site
title: Machine Learning Training for Text Emotion Detection

# A brief description of your site
description: Central hub and bookmark for the 17-week training course on Machine Learning with a focus on Natural Language Processing.

# The base URL of your site (optional)
# e.g., /my-course-site
# baseurl: "/my-course-site"

# The URL of your site (optional)
# e.g., https://username.github.io
# url: "https://langure.github.io"

# Optional: Author information
author:
  name: Alejandro De León Languré
  email: a00932741@tec.mx

# Optional: Enable specific plugins (if needed and supported by theme/GitHub Pages)
# plugins:
#   - jekyll-seo-tag
#   - jekyll-feed
